language: cpp

matrix:
  include:
    - os: linux
      dist: bionic
      compiler: gcc
      addons:
        apt:
          update: true
          packages:
            - libcurl4-nss-dev
            - libgoogle-glog-dev
            - libtool
            - libx11-dev

install:
  - pip install --user cpp-coveralls

script:
  - cd $TRAVIS_BUILD_DIR
  - ./bin/build.sh -t
  - make -C build/ubuntu_x86_64 test

after_success:
  - coveralls -b ./build/ubuntu_x86_64/test/CMakeFiles/colonio_test.dir/__/ -i src --gcov-options '\-lp'
